export const EFM_SOURCE_MODULES = [
  'purchase',
  'sales',
  'inventory',
  'payment',
  'collection',
  'adjustment',
  'return',
  'credit_note',
  'debit_note',
  'transform',
] as const;

export type EfmSourceModule = (typeof EFM_SOURCE_MODULES)[number];

export const DEFAULT_COA_ACCOUNTS = [
  { code: '1', accountKey: 'ACC-1000', name: 'Activo', accountType: 'header', nature: 'asset', hierarchyLevel: 0 },
  { code: '11', accountKey: 'ACC-1100', name: 'Activo corriente', accountType: 'header', nature: 'asset', parentAccountKey: 'ACC-1000', hierarchyLevel: 1 },
  { code: '1105', accountKey: 'ACC-1105', name: 'Caja', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1100', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '1110', accountKey: 'ACC-1110', name: 'Bancos', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1100', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '1305', accountKey: 'ACC-1305', name: 'Clientes', accountType: 'control', nature: 'asset', parentAccountKey: 'ACC-1100', hierarchyLevel: 2, isControl: true, isPostingAllowed: true },
  { code: '14', accountKey: 'ACC-1400', name: 'Inventarios', accountType: 'header', nature: 'asset', parentAccountKey: 'ACC-1000', hierarchyLevel: 1 },
  { code: '1435', accountKey: 'ACC-1435', name: 'Mercancías no fabricadas', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1400', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '2', accountKey: 'ACC-2000', name: 'Pasivo', accountType: 'header', nature: 'liability', hierarchyLevel: 0 },
  { code: '22', accountKey: 'ACC-2200', name: 'Pasivo corriente', accountType: 'header', nature: 'liability', parentAccountKey: 'ACC-2000', hierarchyLevel: 1 },
  { code: '2205', accountKey: 'ACC-2205', name: 'Proveedores', accountType: 'control', nature: 'liability', parentAccountKey: 'ACC-2200', hierarchyLevel: 2, isControl: true, isPostingAllowed: true },
  { code: '2408', accountKey: 'ACC-2408', name: 'IVA por pagar', accountType: 'tax', nature: 'liability', parentAccountKey: 'ACC-2200', hierarchyLevel: 2, isTax: true, isPostingAllowed: true },
  { code: '4', accountKey: 'ACC-4000', name: 'Ingresos', accountType: 'header', nature: 'revenue', hierarchyLevel: 0 },
  { code: '4135', accountKey: 'ACC-4135', name: 'Comercio al por mayor y menor', accountType: 'detail', nature: 'revenue', parentAccountKey: 'ACC-4000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '5', accountKey: 'ACC-5000', name: 'Gastos', accountType: 'header', nature: 'expense', hierarchyLevel: 0 },
  { code: '6135', accountKey: 'ACC-6135', name: 'Comercio al por mayor y menor', accountType: 'detail', nature: 'expense', parentAccountKey: 'ACC-5000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '613595', accountKey: 'ACC-613595', name: 'Devoluciones en ventas', accountType: 'detail', nature: 'expense', parentAccountKey: 'ACC-5000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '15', accountKey: 'ACC-1500', name: 'Propiedad planta y equipo', accountType: 'header', nature: 'asset', parentAccountKey: 'ACC-1000', hierarchyLevel: 1 },
  { code: '1520', accountKey: 'ACC-1520', name: 'Maquinaria y equipo', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1500', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '1592', accountKey: 'ACC-1592', name: 'Depreciación acumulada PPE', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1500', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '16', accountKey: 'ACC-1600', name: 'Intangibles', accountType: 'header', nature: 'asset', parentAccountKey: 'ACC-1000', hierarchyLevel: 1 },
  { code: '1610', accountKey: 'ACC-1610', name: 'Software y licencias', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1600', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '1620', accountKey: 'ACC-1620', name: 'Amortización acumulada', accountType: 'detail', nature: 'asset', parentAccountKey: 'ACC-1600', hierarchyLevel: 2, isPostingAllowed: true },
  { code: '5160', accountKey: 'ACC-5160', name: 'Depreciaciones', accountType: 'detail', nature: 'expense', parentAccountKey: 'ACC-5000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '5165', accountKey: 'ACC-5165', name: 'Amortizaciones', accountType: 'detail', nature: 'expense', parentAccountKey: 'ACC-5000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '4210', accountKey: 'ACC-4210', name: 'Utilidad en venta activos', accountType: 'detail', nature: 'revenue', parentAccountKey: 'ACC-4000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '5395', accountKey: 'ACC-5395', name: 'Pérdida en venta/baja activos', accountType: 'detail', nature: 'expense', parentAccountKey: 'ACC-5000', hierarchyLevel: 1, isPostingAllowed: true },
  { code: '5905', accountKey: 'ACC-5905', name: 'Deterioro de activos', accountType: 'detail', nature: 'expense', parentAccountKey: 'ACC-5000', hierarchyLevel: 1, isPostingAllowed: true },
] as const;

export const DEFAULT_ACCOUNTING_RULES = [
  {
    ruleKey: 'RULE-SALES-INVOICE',
    name: 'Facturación ventas',
    sourceModule: 'sales',
    eventType: 'EscmInvoiceIssued',
    debitAccountKey: 'ACC-1305',
    creditAccountKey: 'ACC-4135',
    priority: 10,
  },
  {
    ruleKey: 'RULE-SALES-PAYMENT',
    name: 'Recaudo clientes',
    sourceModule: 'collection',
    eventType: 'EscmPaymentConfirmed',
    debitAccountKey: 'ACC-1110',
    creditAccountKey: 'ACC-1305',
    priority: 10,
  },
  {
    ruleKey: 'RULE-PURCHASE-SETTLEMENT',
    name: 'Liquidación compras',
    sourceModule: 'purchase',
    eventType: 'CoffeeSettlementPosted',
    debitAccountKey: 'ACC-1435',
    creditAccountKey: 'ACC-2205',
    priority: 10,
  },
  {
    ruleKey: 'RULE-INVENTORY-RECEIPT',
    name: 'Entrada inventario',
    sourceModule: 'inventory',
    eventType: 'EimsMovementPosted',
    debitAccountKey: 'ACC-1435',
    creditAccountKey: 'ACC-2205',
    priority: 20,
  },
  {
    ruleKey: 'RULE-INVENTORY-ISSUE',
    name: 'Salida inventario',
    sourceModule: 'inventory',
    eventType: 'EimsMovementIssued',
    debitAccountKey: 'ACC-6135',
    creditAccountKey: 'ACC-1435',
    priority: 20,
  },
  {
    ruleKey: 'RULE-RETURN',
    name: 'Devoluciones ventas',
    sourceModule: 'return',
    eventType: 'EscmReturnProcessed',
    debitAccountKey: 'ACC-613595',
    creditAccountKey: 'ACC-1305',
    priority: 15,
  },
  {
    ruleKey: 'RULE-CREDIT-NOTE',
    name: 'Nota crédito',
    sourceModule: 'credit_note',
    eventType: 'EscmCreditNoteIssued',
    debitAccountKey: 'ACC-613595',
    creditAccountKey: 'ACC-1305',
    priority: 15,
  },
  {
    ruleKey: 'RULE-DEBIT-NOTE',
    name: 'Nota débito',
    sourceModule: 'debit_note',
    eventType: 'EscmDebitNoteIssued',
    debitAccountKey: 'ACC-1305',
    creditAccountKey: 'ACC-4135',
    priority: 15,
  },
  {
    ruleKey: 'RULE-ADJUSTMENT',
    name: 'Ajustes contables',
    sourceModule: 'adjustment',
    eventType: 'EfmManualAdjustment',
    debitAccountKey: 'ACC-6135',
    creditAccountKey: 'ACC-1435',
    priority: 50,
  },
  {
    ruleKey: 'RULE-TRANSFORM',
    name: 'Transformaciones inventario',
    sourceModule: 'transform',
    eventType: 'EimsTransformPosted',
    debitAccountKey: 'ACC-1435',
    creditAccountKey: 'ACC-1435',
    priority: 30,
  },
  {
    ruleKey: 'RULE-AP-INVOICE',
    name: 'Factura proveedor CxP',
    sourceModule: 'purchase',
    eventType: 'EfmApInvoicePosted',
    debitAccountKey: 'ACC-1435',
    creditAccountKey: 'ACC-2205',
    priority: 10,
  },
  {
    ruleKey: 'RULE-AP-PAYMENT',
    name: 'Pago proveedor',
    sourceModule: 'payment',
    eventType: 'EfmApPaymentProcessed',
    debitAccountKey: 'ACC-2205',
    creditAccountKey: 'ACC-1110',
    priority: 10,
  },
  {
    ruleKey: 'RULE-TR-MOVEMENT',
    name: 'Movimiento tesorería',
    sourceModule: 'treasury',
    eventType: 'EfmTrMovementProcessed',
    debitAccountKey: 'ACC-1110',
    creditAccountKey: 'ACC-1105',
    priority: 10,
  },
  {
    ruleKey: 'RULE-TR-AR-COLLECTION',
    name: 'Recaudo tesorería',
    sourceModule: 'treasury',
    eventType: 'EfmTrMovementProcessed',
    debitAccountKey: 'ACC-1110',
    creditAccountKey: 'ACC-1305',
    priority: 15,
  },
  {
    ruleKey: 'RULE-FA-ACQUISITION',
    name: 'Alta activo fijo',
    sourceModule: 'fixed_assets',
    eventType: 'EfmFaAssetActivated',
    debitAccountKey: 'ACC-1520',
    creditAccountKey: 'ACC-2205',
    priority: 10,
  },
  {
    ruleKey: 'RULE-FA-DEPRECIATION',
    name: 'Depreciación periódica',
    sourceModule: 'fixed_assets',
    eventType: 'EfmFaDepreciationPosted',
    debitAccountKey: 'ACC-5160',
    creditAccountKey: 'ACC-1592',
    priority: 10,
  },
  {
    ruleKey: 'RULE-FA-AMORTIZATION',
    name: 'Amortización intangibles',
    sourceModule: 'fixed_assets',
    eventType: 'EfmFaAmortizationPosted',
    debitAccountKey: 'ACC-5165',
    creditAccountKey: 'ACC-1620',
    priority: 10,
  },
  {
    ruleKey: 'RULE-FA-DISPOSAL',
    name: 'Baja de activo',
    sourceModule: 'fixed_assets',
    eventType: 'EfmFaDisposalPosted',
    debitAccountKey: 'ACC-1592',
    creditAccountKey: 'ACC-1520',
    priority: 10,
  },
  {
    ruleKey: 'RULE-FA-REVALUATION',
    name: 'Revalorización activo',
    sourceModule: 'fixed_assets',
    eventType: 'EfmFaRevaluationPosted',
    debitAccountKey: 'ACC-1520',
    creditAccountKey: 'ACC-5905',
    priority: 15,
  },
] as const;

export const DEFAULT_PARAMETERS = [
  { parameterKey: 'base_currency', name: 'Moneda base', value: { currencyKey: 'COP' } },
  { parameterKey: 'auto_post_journals', name: 'Contabilizar automáticamente', value: { enabled: true } },
  { parameterKey: 'require_balanced_entries', name: 'Exigir partida doble', value: { enabled: true } },
  { parameterKey: 'default_company', name: 'Empresa por defecto', value: { companyKey: 'CO-MAIN' } },
  {
    parameterKey: 'ap_validation_tolerances',
    name: 'Tolerancias validación facturas CxP',
    value: { quantityPercent: 2, pricePercent: 1, taxPercent: 0.5, discountPercent: 1 },
  },
] as const;

export const DEFAULT_COMPANY = {
  companyKey: 'CO-MAIN',
  legalName: 'Empresa principal',
  baseCurrency: 'COP',
  isDefault: true,
};

export const DEFAULT_CURRENCIES = [
  { currencyKey: 'COP', name: 'Peso colombiano', symbol: '$', exchangeRate: 1, isBase: true },
  { currencyKey: 'USD', name: 'Dólar estadounidense', symbol: 'US$', exchangeRate: 4000, isBase: false },
] as const;
