import type { FormFieldDefinition } from '../api/forms';

export type StudioComponentDef = {
  id: string;
  group: string;
  label: string;
  type: string;
  icon?: string;
  description: string;
  useCases: string[];
  configTips: string[];
  example: string;
  commonErrors: string[];
  createField: (index: number) => FormFieldDefinition;
};

const SI_NO = [
  { value: 'si', label: 'Sí' },
  { value: 'no', label: 'No' },
];

function base(key: string, type: string, label: string, extra: Partial<FormFieldDefinition> = {}): FormFieldDefinition {
  return { key, type, label, ...extra };
}

export const STUDIO_COMPONENT_GROUPS = [
  'Texto y datos',
  'Selección',
  'Fecha y hora',
  'Multimedia',
  'Ubicación',
  'Códigos',
  'Layout',
  'Avanzado',
] as const;

export const STUDIO_COMPONENTS: StudioComponentDef[] = [
  {
    id: 'text',
    group: 'Texto y datos',
    label: 'Texto corto',
    type: 'text',
    description: 'Campo de una línea para nombres, códigos o respuestas breves.',
    useCases: ['Nombre', 'Código interno', 'Placa', 'Referencia'],
    configTips: ['Use validación pattern para formatos', 'Combine con visibleWhen para campos condicionales'],
    example: 'Nombre del operario',
    commonErrors: ['Claves duplicadas', 'Etiquetas genéricas sin contexto'],
    createField: (i) => base(`texto_${i}`, 'text', 'Texto corto'),
  },
  {
    id: 'textarea',
    group: 'Texto y datos',
    label: 'Texto largo',
    type: 'textarea',
    description: 'Varias líneas para observaciones, narrativas o comentarios.',
    useCases: ['Observaciones', 'Diagnóstico', 'Notas de visita'],
    configTips: ['Marque requiredWhen si depende de otra respuesta'],
    example: 'Descripción del hallazgo en campo',
    commonErrors: ['Hacer obligatorio sin límite de longitud en móvil'],
    createField: (i) => base(`texto_largo_${i}`, 'textarea', 'Texto largo'),
  },
  {
    id: 'email',
    group: 'Texto y datos',
    label: 'Correo electrónico',
    type: 'text',
    description: 'Texto con validación de email en web y teclado adecuado en móvil.',
    useCases: ['Contacto cliente', 'Notificaciones', 'Login alternativo'],
    configTips: ['metadata.inputType = email'],
    example: 'correo@empresa.com',
    commonErrors: ['Olvidar el @ en validación manual'],
    createField: (i) => base(`email_${i}`, 'text', 'Correo electrónico', {
      metadata: { inputType: 'email' },
      validation: { pattern: '^[^@]+@[^@]+\\.[^@]+$' },
    }),
  },
  {
    id: 'phone',
    group: 'Texto y datos',
    label: 'Teléfono',
    type: 'text',
    description: 'Número telefónico con teclado numérico en dispositivos móviles.',
    useCases: ['WhatsApp', 'Contacto de emergencia', 'Proveedor'],
    configTips: ['metadata.inputType = tel'],
    example: '+57 300 123 4567',
    commonErrors: ['Mezclar código país en distintos formatos'],
    createField: (i) => base(`telefono_${i}`, 'text', 'Teléfono', { metadata: { inputType: 'tel' } }),
  },
  {
    id: 'url',
    group: 'Texto y datos',
    label: 'URL',
    type: 'text',
    description: 'Enlace web verificable.',
    useCases: ['Sitio del proveedor', 'Documento en línea'],
    configTips: ['metadata.inputType = url'],
    example: 'https://agroerp.com',
    commonErrors: ['Olvidar https:// en validación'],
    createField: (i) => base(`url_${i}`, 'text', 'Sitio web', { metadata: { inputType: 'url' } }),
  },
  {
    id: 'number',
    group: 'Texto y datos',
    label: 'Número',
    type: 'number',
    description: 'Valores numéricos con min/max opcionales.',
    useCases: ['Cantidad', 'Edad', 'Dosis', 'Área'],
    configTips: ['validation.min / validation.max'],
    example: 'Hectáreas sembradas',
    commonErrors: ['Usar text para números sin validación'],
    createField: (i) => base(`numero_${i}`, 'number', 'Número', { validation: { min: 0 } }),
  },
  {
    id: 'currency',
    group: 'Texto y datos',
    label: 'Moneda',
    type: 'currency',
    description: 'Montos monetarios.',
    useCases: ['Costo', 'Precio de venta', 'Presupuesto'],
    configTips: ['Prefijo COP/USD en metadata si aplica'],
    example: 'Valor de la compra',
    commonErrors: ['No definir decimales en culturas que usan coma'],
    createField: (i) => base(`moneda_${i}`, 'currency', 'Valor (COP)', { metadata: { currency: 'COP' } }),
  },
  {
    id: 'color',
    group: 'Texto y datos',
    label: 'Selector de color',
    type: 'text',
    description: 'Selector visual de color (web) / texto hex (móvil).',
    useCases: ['Categorización visual', 'Estado de lote'],
    configTips: ['metadata.inputType = color'],
    example: 'Color de etiqueta',
    commonErrors: ['Esperar picker nativo en todas las versiones Android'],
    createField: (i) => base(`color_${i}`, 'text', 'Color', { metadata: { inputType: 'color' }, defaultValue: '#2d6a4f' }),
  },
  {
    id: 'select',
    group: 'Selección',
    label: 'Select',
    type: 'select',
    description: 'Lista desplegable de una sola opción.',
    useCases: ['Cultivo', 'Turno', 'Bodega'],
    configTips: ['options[] o metadata.catalogKey para listas dinámicas'],
    example: 'Tipo de cultivo',
    commonErrors: ['Opciones sin value estable'],
    createField: (i) => base(`select_${i}`, 'select', 'Selección', { options: [...SI_NO] }),
  },
  {
    id: 'multi_select',
    group: 'Selección',
    label: 'Select múltiple',
    type: 'multi_select',
    description: 'Varias opciones simultáneas.',
    useCases: ['Síntomas', 'EPP usados', 'Actividades'],
    configTips: ['Valor guardado como array'],
    example: 'Equipos de protección',
    commonErrors: ['Validar como string en lugar de array'],
    createField: (i) => base(`multi_${i}`, 'multi_select', 'Selección múltiple', {
      options: [
        { value: 'a', label: 'Opción A' },
        { value: 'b', label: 'Opción B' },
      ],
    }),
  },
  {
    id: 'radio',
    group: 'Selección',
    label: 'Radio',
    type: 'radio',
    description: 'Una opción visible entre varias (ideal Sí/No).',
    useCases: ['¿Acepta términos?', '¿Cumple calidad?'],
    configTips: ['Combine con visibleWhen en campos siguientes'],
    example: '¿Requiere seguimiento?',
    commonErrors: ['Demasiadas opciones en móvil — preferir select'],
    createField: (i) => base(`radio_${i}`, 'radio', 'Opción única', { options: [...SI_NO] }),
  },
  {
    id: 'checkbox',
    group: 'Selección',
    label: 'Checkbox / Switch',
    type: 'boolean',
    description: 'Verdadero/falso o grupo de casillas.',
    useCases: ['Activar sección', 'Confirmación', 'EPI completo'],
    configTips: ['boolean para switch simple', 'checkbox + options para grupo'],
    example: '¿Acepta los términos?',
    commonErrors: ['Olvidar requiredWhen para firma posterior'],
    createField: (i) => base(`switch_${i}`, 'boolean', '¿Activar opción?'),
  },
  {
    id: 'autocomplete',
    group: 'Selección',
    label: 'Autocompletar',
    type: 'autocomplete',
    description: 'Búsqueda con sugerencias.',
    useCases: ['Cliente', 'Producto', 'Empleado'],
    configTips: ['options o apiSource en schema avanzado'],
    example: 'Buscar proveedor',
    commonErrors: ['Lista muy larga sin filtro'],
    createField: (i) => base(`autocomplete_${i}`, 'autocomplete', 'Autocompletar', {
      options: [
        { value: '1', label: 'Opción sugerida 1' },
        { value: '2', label: 'Opción sugerida 2' },
      ],
    }),
  },
  {
    id: 'date',
    group: 'Fecha y hora',
    label: 'Fecha',
    type: 'date',
    description: 'Selector de fecha.',
    useCases: ['Fecha de visita', 'Vencimiento', 'Siembra'],
    configTips: ['defaultValue en ISO si aplica'],
    example: 'Fecha de aplicación',
    commonErrors: ['Confundir con datetime'],
    createField: (i) => base(`fecha_${i}`, 'date', 'Fecha'),
  },
  {
    id: 'time',
    group: 'Fecha y hora',
    label: 'Hora',
    type: 'time',
    description: 'Hora del día.',
    useCases: ['Hora de inicio', 'Turno'],
    configTips: ['Formato HH:mm'],
    example: 'Hora de riego',
    commonErrors: ['En Android antiguo puede ser texto — validar pattern'],
    createField: (i) => base(`hora_${i}`, 'time', 'Hora'),
  },
  {
    id: 'datetime',
    group: 'Fecha y hora',
    label: 'Fecha y hora',
    type: 'datetime',
    description: 'Marca temporal completa.',
    useCases: ['Recepción', 'Muestreo', 'Incidente'],
    configTips: ['Útil con GPS para trazabilidad'],
    example: 'Fecha y hora de muestreo',
    commonErrors: ['Zona horaria no explícita en reportes'],
    createField: (i) => base(`fecha_hora_${i}`, 'datetime', 'Fecha y hora'),
  },
  {
    id: 'photo',
    group: 'Multimedia',
    label: 'Fotografía',
    type: 'photo',
    description: 'Una foto desde cámara o galería.',
    useCases: ['Evidencia', 'Plaga', 'EPI'],
    configTips: ['Funciona offline en móvil — sync después'],
    example: 'Foto del lote',
    commonErrors: ['No pedir foto sin visibleWhen cuando no aplica'],
    createField: (i) => base(`foto_${i}`, 'photo', 'Fotografía'),
  },
  {
    id: 'gallery',
    group: 'Multimedia',
    label: 'Galería (varias fotos)',
    type: 'gallery',
    description: 'Múltiples imágenes.',
    useCases: ['Antes/después', 'Varias muestras'],
    configTips: ['metadata.maxFiles para límite'],
    example: 'Fotos del cultivo',
    commonErrors: ['Archivos muy pesados sin compresión en móvil'],
    createField: (i) => base(`galeria_${i}`, 'gallery', 'Galería de fotos', { metadata: { maxFiles: 5 } }),
  },
  {
    id: 'signature',
    group: 'Multimedia',
    label: 'Firma digital',
    type: 'signature',
    description: 'Firma en pantalla.',
    useCases: ['Aceptación', 'Conformidad', 'Entrega'],
    configTips: ['visibleWhen tras aceptar términos'],
    example: 'Firma del responsable',
    commonErrors: ['Obligatoria sin mostrar el campo'],
    createField: (i) => base(`firma_${i}`, 'signature', 'Firma digital'),
  },
  {
    id: 'audio',
    group: 'Multimedia',
    label: 'Audio',
    type: 'audio',
    description: 'Nota de voz.',
    useCases: ['Observación hablada', 'Entrevista'],
    configTips: ['Permisos de micrófono en móvil'],
    example: 'Nota de voz',
    commonErrors: ['No indicar duración máxima'],
    createField: (i) => base(`audio_${i}`, 'audio', 'Grabación de audio'),
  },
  {
    id: 'video',
    group: 'Multimedia',
    label: 'Video',
    type: 'video',
    description: 'Clip de video.',
    useCases: ['Demostración', 'Capacitación en campo'],
    configTips: ['Peso alto — Wi‑Fi recomendado para sync'],
    example: 'Video de aplicación',
    commonErrors: ['Videos largos sin límite'],
    createField: (i) => base(`video_${i}`, 'video', 'Video'),
  },
  {
    id: 'file',
    group: 'Multimedia',
    label: 'Adjuntos',
    type: 'file',
    description: 'Documentos PDF, Excel, etc.',
    useCases: ['Factura', 'Certificado', 'Hoja de seguridad'],
    configTips: ['accept en metadata: .pdf,.xlsx'],
    example: 'Adjuntar documento',
    commonErrors: ['Tipos de archivo no restringidos'],
    createField: (i) => base(`archivo_${i}`, 'file', 'Adjunto', { metadata: { accept: '.pdf,.jpg,.png' } }),
  },
  {
    id: 'geo',
    group: 'Ubicación',
    label: 'GPS',
    type: 'geo',
    description: 'Coordenadas con precisión.',
    useCases: ['Lote', 'Punto de muestreo', 'Incidente'],
    configTips: ['settings.requireGps a nivel formulario', 'validation.maxAccuracyMeters'],
    example: 'Ubicación del registro',
    commonErrors: ['GPS en interiores sin aviso al usuario'],
    createField: (i) => base(`gps_${i}`, 'geo', 'Ubicación GPS', { validation: { maxAccuracyMeters: 50 } }),
  },
  {
    id: 'map',
    group: 'Ubicación',
    label: 'Mapa',
    type: 'map',
    description: 'Mapa interactivo (web) / GPS en móvil.',
    useCases: ['Selección visual de parcela'],
    configTips: ['Complementa geo'],
    example: 'Marcar en mapa',
    commonErrors: ['Esperar mapa offline completo'],
    createField: (i) => base(`mapa_${i}`, 'map', 'Mapa'),
  },
  {
    id: 'qrcode',
    group: 'Códigos',
    label: 'Código QR',
    type: 'qrcode',
    description: 'Escaneo QR.',
    useCases: ['Lote', 'Activo', 'Insumo'],
    configTips: ['Cámara trasera en móvil'],
    example: 'Escanear QR del lote',
    commonErrors: ['No validar formato del código leído'],
    createField: (i) => base(`qr_${i}`, 'qrcode', 'Código QR'),
  },
  {
    id: 'barcode',
    group: 'Códigos',
    label: 'Código de barras',
    type: 'barcode',
    description: 'Escaneo de barras.',
    useCases: ['Inventario', 'Producto'],
    configTips: ['Igual que QR en móvil'],
    example: 'Escanear producto',
    commonErrors: ['Confundir con campo texto manual'],
    createField: (i) => base(`barcode_${i}`, 'barcode', 'Código de barras'),
  },
  {
    id: 'heading',
    group: 'Layout',
    label: 'Título de sección',
    type: 'heading',
    description: 'Encabezado visual / paso en móvil.',
    useCases: ['Separar bloques', 'Wizard en app'],
    configTips: ['Use sections[] para tabs/acordeón'],
    example: 'Datos del responsable',
    commonErrors: ['Demasiados títulos seguidos'],
    createField: (i) => base(`titulo_${i}`, 'heading', 'Título de sección'),
  },
  {
    id: 'separator',
    group: 'Layout',
    label: 'Separador',
    type: 'separator',
    description: 'Línea divisoria.',
    useCases: ['Agrupar visualmente'],
    configTips: ['Sin valor en envíos'],
    example: '—',
    commonErrors: ['Usar en exceso'],
    createField: (i) => base(`sep_${i}`, 'separator', '—'),
  },
  {
    id: 'html',
    group: 'Layout',
    label: 'Acordeón / HTML',
    type: 'html',
    description: 'Contenido HTML o bloque informativo. metadata.layout=accordion para acordeón.',
    useCases: ['Términos legales', 'Instrucciones'],
    configTips: ['description contiene HTML', 'metadata.layout'],
    example: 'Texto de política',
    commonErrors: ['HTML no sanitizado en fuentes externas'],
    createField: (i) => base(`html_${i}`, 'html', 'Bloque informativo', {
      description: '<p>Contenido editable en el inspector.</p>',
      metadata: { layout: 'accordion', accordionTitle: 'Más información' },
    }),
  },
  {
    id: 'repeat_group',
    group: 'Avanzado',
    label: 'Tabla repetitiva',
    type: 'repeat_group',
    description: 'Filas repetibles (subcampos en fields[]).',
    useCases: ['Varios productos', 'Múltiples trabajadores'],
    configTips: ['Defina fields[] anidados en JSON / reglas'],
    example: 'Lista de insumos aplicados',
    commonErrors: ['UI anidada aún limitada — probar en simulador'],
    createField: (i) => base(`repetir_${i}`, 'repeat_group', 'Grupo repetible', {
      fields: [
        base('item_nombre', 'text', 'Ítem'),
        base('item_cantidad', 'number', 'Cantidad'),
      ],
    }),
  },
  {
    id: 'subform',
    group: 'Avanzado',
    label: 'Subformulario',
    type: 'subform',
    description: 'Bloque de campos reutilizable.',
    useCases: ['Datos del acudiente', 'Detalle de maquinaria'],
    configTips: ['Alias de repeat_group en backend'],
    example: 'Información del acudiente',
    commonErrors: ['No definir fields[] internos'],
    createField: (i) => base(`subform_${i}`, 'subform', 'Subformulario', {
      fields: [
        base('sub_nombre', 'text', 'Nombre'),
        base('sub_telefono', 'text', 'Teléfono', { metadata: { inputType: 'tel' } }),
      ],
    }),
  },
  {
    id: 'calculated',
    group: 'Avanzado',
    label: 'Campo calculado',
    type: 'calculated',
    description: 'Valor automático por expresión.',
    useCases: ['Total', 'Rendimiento estimado'],
    configTips: ['calculate.expression con {campo}', 'dependsOn[]'],
    example: '{area_ha} * 800',
    commonErrors: ['Referencias a campos ocultos'],
    createField: (i) => base(`calc_${i}`, 'calculated', 'Total calculado', {
      calculate: { expression: '{cantidad} * {precio}', dependsOn: ['cantidad', 'precio'] },
    }),
  },
];

export function getComponentsByGroup() {
  const map = new Map<string, StudioComponentDef[]>();
  for (const g of STUDIO_COMPONENT_GROUPS) map.set(g, []);
  for (const c of STUDIO_COMPONENTS) {
    map.get(c.group)?.push(c);
  }
  return map;
}

export function findComponentByType(type: string): StudioComponentDef | undefined {
  return STUDIO_COMPONENTS.find((c) => c.type === type || c.id === type);
}
